interface KeyMap {
  [key: string]: { id: string; mod?: string | null };
}

export const keyMap: KeyMap = {
  //small caps
  "a": { id: "r2k2" },
  "b": { id: "r4k7" },
  "c": { id: "r4k5" },
  "d": { id: "r3k4" },
  "e": { id: "r2k4" },
  "f": { id: "r3k5" },
  "g": { id: "r3k6" },
  "h": { id: "r3k7" },
  "i": { id: "r2k9" },
  "j": { id: "r3k8" },
  "k": { id: "r3k9" },
  "l": { id: "r3k10" },
  "m": { id: "r3k11" },
  "n": { id: "r4k8" },
  "o": { id: "r2k10" },
  "p": { id: "r2k11" },
  "q": { id: "r3k2" },
  "r": { id: "r2k5" },
  "s": { id: "r3k3" },
  "t": { id: "r2k6" },
  "u": { id: "r2k8" },
  "v": { id: "r4k6" },
  "w": { id: "r4k3" },
  "x": { id: "r4k4" },
  "y": { id: "r2k7" },
  "z": { id: "r2k3" },

  //Capital letters
  "A": { id: "r2k2", mod: "right-shift" },
  "B": { id: "r4k7", mod: "right-shift" },
  "C": { id: "r4k5", mod: "right-shift" },
  "D": { id: "r3k4", mod: "right-shift" },
  "E": { id: "r2k4", mod: "right-shift" },
  "F": { id: "r3k5", mod: "right-shift" },
  "G": { id: "r3k6", mod: "right-shift" },
  "H": { id: "r3k7", mod: "left-shift" },
  "I": { id: "r2k9", mod: "left-shift" },
  "J": { id: "r3k8", mod: "left-shift" },
  "K": { id: "r3k9", mod: "left-shift" },
  "L": { id: "r3k10", mod: "left-shift" },
  "M": { id: "r3k11", mod: "left-shift" },
  "N": { id: "r4k8", mod: "left-shift" },
  "O": { id: "r2k10", mod: "left-shift" },
  "P": { id: "r2k11", mod: "left-shift" },
  "Q": { id: "r3k2", mod: "right-shift" },
  "R": { id: "r2k5", mod: "right-shift" },
  "S": { id: "r3k3", mod: "right-shift" },
  "T": { id: "r2k6", mod: "right-shift" },
  "U": { id: "r2k8", mod: "left-shift" },
  "V": { id: "r4k6", mod: "right-shift" },
  "W": { id: "r4k3", mod: "shright-shiftift" },
  "X": { id: "r4k4", mod: "right-shift" },
  "Y": { id: "r2k7", mod: "left-shift" },
  "Z": { id: "r2k3", mod: "right-shift" },

  //Numbers
  "1": { id: "r1k2", mod: "right-shift" },
  "2": { id: "r1k3", mod: "right-shift" },
  "3": { id: "r1k4", mod: "right-shift" },
  "4": { id: "r1k5", mod: "right-shift" },
  "5": { id: "r1k6", mod: "right-shift" },
  "6": { id: "r1k7", mod: "left-shift" },
  "7": { id: "r1k8", mod: "left-shift" },
  "8": { id: "r1k9", mod: "left-shift" },
  "9": { id: "r1k10", mod: "left-shift" },
  "0": { id: "r1k11", mod: "left-shift" },

  //Special characters
  "&": { id: "r1k2" },
  "é": { id: "r1k3" },
  '"': { id: "r1k4" },
  "'": { id: "r1k5" },
  "(": { id: "r1k6" },
  "-": { id: "r1k7" },
  "è": { id: "r1k8" },
  "_": { id: "r1k9" },
  "ç": { id: "r1k10" },
  "à": { id: "r1k11" },
  ")": { id: "r1k12" },
  "=": { id: "r1k13" },
  "~": { id: "r1k3", mod: "altGr" },
  "#": { id: "r1k4", mod: "altGr" },
  "{": { id: "r1k5", mod: "altGr" },
  "[": { id: "r1k6", mod: "altGr" },
  "|": { id: "r1k7", mod: "altGr" },
  "`": { id: "r1k8", mod: "altGr" },
  "Backslash": { id: "r1k9", mod: "altGr" },
  "@": { id: "r1k11", mod: "altGr" },
  "]": { id: "r1k12", mod: "altGr" },
  "}": { id: "r1k13", mod: "altGr" },
  "€": { id: "r2k4", mod: "altGr" },
  "¨": { id: "r2k12", mod: "altGr" },
  "^": { id: "r2k12", mod: "left-shift" },
 "$": { id: "r2k13" },
  "£": { id: "r2k13", mod: "left-shift" },
  "¤": { id: "r2k13", mod: "altGr" },
  "ù": { id: "r3k12"},
  "%": { id: "r3k12", mod: "left-shift" },
    "*": { id: "r3k13" },
    "µ": { id: "r3k13", mod: "left-shift" },
    "<": { id: "r4k2" },
    ">": { id: "r4k2", mod:"right-shift" },
    ",": { id: "r4k9" },
    "?": { id: "r4k9", mod: "left-shift" },
    ";": {id:"r4k10"},
    ".":{id:"r4k10", mod:"left-shift"},
    "slash":{id:"r4k11", mod:"left-shift"},
    "!":{id:"r4k11"},
    "§":{id:"r4k11", mod:"left-shift"},

    //Others
    "esc":{id:"r1k1"},
    "back":{id:"r1k14"},
    "tab":{id:"r2k1"},
    "enter":{id:"r2k14"},
    "capLock":{id:"r3k1"},
    "left-shift":{id:"r4k1"},
    "right-shift":{id:"r4k13"},
    "altGr":{id:"r5k5"},
    "space":{id: "r5k4"}

};
